apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-api
  namespace: games
  labels:
    app: games-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: games-api
  template:
    metadata:
      labels:
        app: games-api
    spec:
      containers:
      - name: games-api
        image: alexandresorza/fcg-games-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ApplicationInsights__ConnectionString
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: appinsights-connection-string
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: sql-games-connection
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: servicebus-connection
        - name: ServiceBus__Topics__Games
          valueFrom:
            configMapKeyRef:
              name: fcg-config
              key: TOPIC_GAMES
        - name: MongoSettings__ConnectionString
          valueFrom:
            secretKeyRef:
              name: fcg-secrets
              key: cosmosdb-connection
        - name: MongoSettings__Database
          value: "EventStoreDb"
        - name: MongoSettings__Collection
          value: "Events"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "fcg-keyvault-secrets"

