apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: games-api-ingress
  namespace: games
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /games(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: games-api
            port:
              number: 80
